In [1]:
# import libraries
import pandas as pd

In [2]:
# read the data file and create a data frame
oo = pd.read_csv('./olympics.csv')

#### Sanity Checks

In [3]:
# get the size of the dataframe
oo.shape

(29216, 10)

In [4]:
# get the top five lines of data
oo.head(5)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [5]:
# get the last five lines of data
oo.tail(5)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [6]:
# get information about the columns
oo.info()

<class 'pandas.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          29216 non-null  str
 1   Edition       29216 non-null  int64
 2   Sport         29216 non-null  str
 3   Discipline    29216 non-null  str
 4   Athlete       29216 non-null  str
 5   NOC           29216 non-null  str
 6   Gender        29216 non-null  str
 7   Event         29216 non-null  str
 8   Event_gender  29216 non-null  str
 9   Medal         29216 non-null  str
dtypes: int64(1), str(9)
memory usage: 2.2 MB

NOC = National Olympic Committee

In [7]:
# gives statistics of entire data
oo.describe()

            Edition
count  29216.000000
mean    1967.713171
std       32.406293
min     1896.000000
25%     1948.000000
50%     1976.000000
75%     1996.000000
max     2008.000000

In [8]:
# obtain 5 random lines of data
oo.sample(5)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
19371,Seoul,1988,Shooting,Shooting,"SCHUMANN, Ralf",GDR,Men,25m rapid fire pistol (60 shots),M,Silver
20270,Barcelona,1992,Canoe / Kayak,Canoe / Kayak F,"DONUSZ, Eva",HUN,Women,K-2 500m (kayak double),W,Bronze
27592,Beijing,2008,Athletics,Athletics,"WILLIAMS, Shericka",JAM,Women,400m,W,Silver
16726,Los Angeles,1984,Aquatics,Swimming,"HAYES, Lawrence Bruce",USA,Men,4x200m freestyle relay,M,Gold
21871,Atlanta,1996,Basketball,Basketball,"PAYTON, Gary",USA,Men,basketball,M,Gold

#### Manipulating Columns

In [9]:
# rename columns
mapper = {'Edition': 'Year', 'Athlete': 'Athlete_Name', 'Event_gender': 'Event_Gender'}
oo = oo.rename(columns = mapper)

In [10]:
# check column names
oo.columns

Index(['City', 'Year', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
       'Event', 'Event_Gender', 'Medal'],
      dtype='str')

In [11]:
# find the years that the Olympics was held
oo.Year.unique()

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008])

In [12]:
# find the different sporting events
oo.Sport.unique()

<StringArray>
[         'Aquatics',         'Athletics',           'Cycling',
           'Fencing',        'Gymnastics',          'Shooting',
            'Tennis',     'Weightlifting',         'Wrestling',
           'Archery',     'Basque Pelota',           'Cricket',
           'Croquet',        'Equestrian',          'Football',
              'Golf',              'Polo',            'Rowing',
             'Rugby',           'Sailing',        'Tug of War',
            'Boxing',          'Lacrosse',             'Roque',
            'Hockey',      'Jeu de paume',           'Rackets',
           'Skating', 'Water Motorsports', 'Modern Pentathlon',
        'Ice Hockey',        'Basketball',     'Canoe / Kayak',
          'Handball',              'Judo',        'Volleyball',
      'Table Tennis',         'Badminton',          'Baseball',
          'Softball',         'Taekwondo',         'Triathlon']
Length: 42, dtype: str

In [13]:
# how many sporting events per year
oo.Year.value_counts()

Year
2008    2042
2000    2015
2004    1998
1996    1859
1992    1705
1988    1546
1984    1459
1980    1387
1976    1305
1920    1298
1972    1185
1968    1031
1964    1010
1952     889
1912     885
1956     885
1924     884
1960     882
1936     875
1948     814
1908     804
1928     710
1932     615
1900     512
1904     470
1896     151
Name: count, dtype: int64

#### Add and Remove Columns

In [14]:
# define dictionary
position_dict = {'Gold': 'First', 
                 'Silver': 'Second',
                 'Bronze': 'Third'
                }
position_dict

{'Gold': 'First', 'Silver': 'Second', 'Bronze': 'Third'}

In [15]:
# add a new column
oo['Position'] = oo['Medal'].map(position_dict)

In [16]:
oo.columns

Index(['City', 'Year', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
       'Event', 'Event_Gender', 'Medal', 'Position'],
      dtype='str')

In [17]:
oo.sample(10) # random sample of 10

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
22345,Atlanta,1996,Gymnastics,Artistic G.,"BURINCA, Dan",ROU,Men,rings,M,Silver,Second
4628,Paris,1924,Gymnastics,Artistic G.,"HERMANN, Arthur",FRA,Men,team competition,M,Silver,Second
8605,Helsinki,1952,Gymnastics,Artistic G.,"GULYAS, Karolyne",HUN,Women,team competition,W,Silver,Second
9387,Melbourne / Stockholm,1956,Fencing,Fencing,"PIATKOWSKI, Andrzej Ryszard",POL,Men,sabre team,M,Silver,Second
6075,Los Angeles,1932,Gymnastics,Artistic G.,"NERI, Romeo",ITA,Men,individual all-round,M,Gold,First
18817,Seoul,1988,Football,Football,"KHARIN, Dmitri",URS,Men,football,M,Gold,First
25507,Athens,2004,Aquatics,Water polo,"ROUMPESI, Antigoni",GRE,Women,water polo,W,Silver,Second
24366,Sydney,2000,Gymnastics,Rhythmic G.,"GEORGATOU, Maria",GRE,Women,group competition,W,Bronze,Third
12270,Mexico,1968,Football,Football,"MIYAMOTO, Masakatsu",JPN,Men,football,M,Bronze,Third
16949,Los Angeles,1984,Athletics,Athletics,"JOYNER, Alfredrick Alphonzo",USA,Men,triple jump,M,Gold,First

In [18]:
# remove the column just added
oo = oo.drop('Position', axis = 1)

In [19]:
# check if column was dropped
oo.sample(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
23044,Atlanta,1996,Volleyball,Volleyball,"SOUZA, Helia",BRA,Women,volleyball,W,Bronze
28008,Beijing,2008,Canoe / Kayak,Canoe / Kayak S,"HOCHSCHORNER, Pavol",SVK,Men,C-2 (canoe double),M,Gold
21146,Barcelona,1992,Volleyball,Volleyball,"HILLIARD, Brent William",USA,Men,volleyball,M,Bronze
27336,Beijing,2008,Aquatics,Swimming,"TARGETT, Matt",AUS,Men,4x100m medley relay,M,Silver
25321,Athens,2004,Aquatics,Swimming,"HANSEN, Brendan",USA,Men,4x100m medley relay,M,Gold

#### Manipulating Rows

In [20]:
# get all rows for the first Olympics
first_olympics = (oo.Year == 1896)

In [21]:
oo_1 = oo[first_olympics]

In [22]:
oo_1.head(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [23]:
oo_1.tail(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
146,Athens,1896,Weightlifting,Weightlifting,"JENSEN, Viggo",DEN,Men,heavyweight - two hand lift,M,Gold
147,Athens,1896,Weightlifting,Weightlifting,"ELLIOTT, Launceston",GBR,Men,heavyweight - two hand lift,M,Silver
148,Athens,1896,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,open event,M,Bronze
149,Athens,1896,Wrestling,Wrestling Gre-R,"SCHUMANN, Carl",GER,Men,open event,M,Gold
150,Athens,1896,Wrestling,Wrestling Gre-R,"TSITAS, Georgios",GRE,Men,open event,M,Silver

In [24]:
# get all rows where the Olympics was held in Athens
oo_athens = oo[oo.City == 'Athens']

In [25]:
oo_athens.shape

(2149, 10)

In [26]:
oo_athens.head(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [27]:
oo_athens.tail(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
27169,Athens,2004,Wrestling,Wrestling Gre-R,"GABER IBRAHIM, Karam",EGY,Men,84 - 96kg,M,Gold
27170,Athens,2004,Wrestling,Wrestling Gre-R,"NOZADZE, Ramaz",GEO,Men,84 - 96kg,M,Silver
27171,Athens,2004,Wrestling,Wrestling Gre-R,"GARDNER, Rulon",USA,Men,96 - 120kg,M,Bronze
27172,Athens,2004,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Gold
27173,Athens,2004,Wrestling,Wrestling Gre-R,"TSURTSUMIA, Georgiy",KAZ,Men,96 - 120kg,M,Silver

In [28]:
# compound conditions
oo_2 = oo[(oo.City == 'Athens') & (oo.Year == 2004)]

In [29]:
oo_2.head(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
25176,Athens,2004,Aquatics,Diving,"TIAN, Liang",CHN,Men,10m platform,M,Bronze
25177,Athens,2004,Aquatics,Diving,"HU, Jia",CHN,Men,10m platform,M,Gold
25178,Athens,2004,Aquatics,Diving,"HELM, Mathew",AUS,Men,10m platform,M,Silver
25179,Athens,2004,Aquatics,Diving,"TOURKY, Loudy",AUS,Women,10m platform,W,Bronze
25180,Athens,2004,Aquatics,Diving,"NEWBERY, Chantelle",AUS,Women,10m platform,W,Gold

In [30]:
# another compound condition
oo_3 = oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')]

In [31]:
oo_3 # sample(>4) will not work

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver

In [32]:
# Larisa Latynina - most decorated Female athlete
oo_4 = oo[oo['Athlete_Name'].str.contains("LATYNINA")]

In [33]:
oo_4

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
9445,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold
9453,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Gold
9493,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold
9507,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,"team, portable apparatus",W,Bronze
9528,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Silver
9534,Melbourne / Stockholm,1956,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Gold
10353,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,balance beam,W,Silver
10358,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold
10367,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Gold
10405,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold
10417,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Silver
10421,Rome,1960,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Bronze
11268,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,balance beam,W,Bronze
11275,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold
11286,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Silver
11322,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold
11332,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Bronze
11339,Tokyo,1964,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Silver

#### Sorting a DataFrame and Series (Columns)

In [34]:
# sorting a series (column)
oo['Athlete_Name'].sort_values()

651                 AABYE, Edgar
2849       AALTONEN, Arvo Ossian
2852       AALTONEN, Arvo Ossian
7716    AALTONEN, Paavo Johannes
7730    AALTONEN, Paavo Johannes
                  ...
603                   ÖSTMO, Ole
608                   ÖSTMO, Ole
621                   ÖSTMO, Ole
596                   ÖSTMO, Ole
8051           ÖSTRAND, Per-Olof
Name: Athlete_Name, Length: 29216, dtype: str

In [35]:
#sort data frame
oo_5 = oo.sort_values('Athlete_Name')

In [36]:
oo_5.head(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
651,Paris,1900,Tug of War,Tug of War,"AABYE, Edgar",ZZX,Men,tug of war,M,Gold
2849,Antwerp,1920,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,200m breaststroke,M,Bronze
2852,Antwerp,1920,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,400m breaststroke,M,Bronze
7716,London,1948,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,pommel horse,M,Gold
7730,London,1948,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,team competition,M,Gold

In [37]:
# sort in a different order
oo_6 = oo.sort_values('Athlete_Name', ascending = False)

In [38]:
oo_6.head(5)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
8051,Helsinki,1952,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400m freestyle,M,Bronze
621,Paris,1900,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"free rifle, team",M,Silver
608,Paris,1900,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, standing",M,Silver
603,Paris,1900,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, prone",M,Bronze
596,Paris,1900,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, 3 positions",M,Bronze

In [39]:
## sort with two parametrs
oo_7 = oo.sort_values(by = ['Year', 'Athlete_Name'])

In [40]:
oo_7.head(10)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
110,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"team, parallel bars",M,Silver
111,Athens,1896,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"team, parallel bars",M,Silver
48,Athens,1896,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,individual road race,M,Bronze
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
134,Athens,1896,Tennis,Tennis,"BOLAND, John",ZZX,Men,doubles,M,Gold
140,Athens,1896,Tennis,Tennis,"BOLAND, John",GBR,Men,singles,M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold

In [41]:
# sort by multiple parameters and in different orders
oo_8 = oo.sort_values(by = ['Year', 'Event', 'Medal'], ascending = [True, True, False])

In [42]:
oo_8.head(10)

,City,Year,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
52,Athens,1896,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
51,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold

#### Working with Indices

In [43]:
# access data using row_name, col_name
oo.loc[22719, 'Event']

'eight with coxswain (8+)'

In [44]:
# access data with row_num, col_num
oo.iloc[0, 5]

'HUN'

In [45]:
# access everything in row = 0
oo.iloc[0, :]

City                    Athens
Year                      1896
Sport                 Aquatics
Discipline            Swimming
Athlete_Name     HAJOS, Alfred
NOC                        HUN
Gender                     Men
Event           100m freestyle
Event_Gender                 M
Medal                     Gold
Name: 0, dtype: object

In [46]:
# access everything in row = 0 (non-intuitive)
oo.iloc[0]

City                    Athens
Year                      1896
Sport                 Aquatics
Discipline            Swimming
Athlete_Name     HAJOS, Alfred
NOC                        HUN
Gender                     Men
Event           100m freestyle
Event_Gender                 M
Medal                     Gold
Name: 0, dtype: object

#### Creating Series and Dataframes

In [47]:
# create lists
city = ['London', 'Rio', 'Tokyo']
start_date = ['27th Jul, 2012', '5th Aug, 2016', '23rd July, 2021']

In [48]:
# create a Series
City = pd.Series(city)
City

0    London
1       Rio
2     Tokyo
dtype: str

In [49]:
# create a data frame
df = pd.DataFrame({"City": pd.Series(city),
                   "Start_Fate": pd.Series(start_date)})

In [50]:
df

     City       Start_Fate
0  London   27th Jul, 2012
1     Rio    5th Aug, 2016
2   Tokyo  23rd July, 2021

#### Working with Dates

In [51]:
city = ['Lodon', 'Rio', 'Tokyo']
start_date = ['07-27-2012', '5th Aug, 2016', '23rd July, 2021']
end_date = ['12th Aug, 2012', '21-08-2016', '8th Aug, 2021']

In [58]:
games = pd.DataFrame(zip(city, start_date, end_date),
                     columns = ['City', 'Start_Date', 'End_Date'])
games

    City       Start_Date        End_Date
0  Lodon       07-27-2012  12th Aug, 2012
1    Rio    5th Aug, 2016      21-08-2016
2  Tokyo  23rd July, 2021   8th Aug, 2021

In [59]:
games.dtypes

City          str
Start_Date    str
End_Date      str
dtype: object

In [60]:
# change types
games['Start_Date'] = pd.to_datetime(games['Start_Date'], format = 'mixed') # converts Start_Date to a datetime format
games['End_Date'] = pd.to_datetime(games['End_Date'], format = 'mixed')
games['City'] = games.City.astype('string') # Reinforces City to be a str
games

    City Start_Date   End_Date
0  Lodon 2012-07-27 2012-08-12
1    Rio 2016-08-05 2016-08-21
2  Tokyo 2021-07-23 2021-08-08

In [61]:
# check the data types
games.dtypes

City                  string
Start_Date    datetime64[us]
End_Date      datetime64[us]
dtype: object

In [62]:
# find the duration of the games
games['End_Date'] - games['Start_Date']

0   16 days
1   16 days
2   16 days
dtype: timedelta64[us]

In [63]:
# add a column for the duration
games = games.assign(Duration = games['End_Date'] - games['Start_Date'])
games

    City Start_Date   End_Date Duration
0  Lodon 2012-07-27 2012-08-12  16 days
1    Rio 2016-08-05 2016-08-21  16 days
2  Tokyo 2021-07-23 2021-08-08  16 days

In [65]:
# check the data types (timedelta means difference)
games.dtypes

City                   string
Start_Date     datetime64[us]
End_Date       datetime64[us]
Duration      timedelta64[us]
dtype: object